name: Release

on:
  push:
      tags:
        - 'v*'
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Latest Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.300'
        
    - name: Install NuGet Client
      uses: nuget/setup-nuget@v1
      
    - name: Remove Github NuGet Source
      run: dotnet nuget remove source localPackages

    - name: Add Github NuGet Source
      run: dotnet nuget add source --username byCrookie --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/byCrookie/index.json"

    - name: Test
      run: dotnet test --verbosity normal
      
    - name: Build Console
      run: dotnet build --configuration Release -o publish/console ./src/TypeCode.Console

    - name: Build Console Interactive
      run: dotnet build --configuration Release -o publish/interactive ./src/TypeCode.Console.Interactive

    - name: Build Wpf
      run: dotnet build --configuration Release -o publish/wpf ./src/TypeCode.Wpf

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
          
    - name: Build Wpf Setup
      run: |
        ./src/TypeCode.Wpf.Setup/DownloadAndExtractWix.ps1
        msbuild ./src/TypeCode.Wpf.Setup/TypeCode.Wpf.Setup.wixproj -p:SolutionDir=${{ github.workspace }}
        New-Item -ItemType directory -Path  publish/setup/wpf -Force
        Copy-Item ./src/TypeCode.Wpf.Setup/bin/Release/TypeCode.Wpf.Setup.msi -Destination publish/setup/wpf/TypeCode.Wpf.Setup.msi
      
    - name: Zip Console
      run: Compress-Archive -Path ./publish/console/* -DestinationPath TypeCode.Console_${{ steps.previoustag.outputs.tag }}.zip

    - name: Zip Console Interactive
      run: Compress-Archive -Path ./publish/interactive/* -DestinationPath TypeCode.Console.Interactive_${{ steps.previoustag.outputs.tag }}.zip

    - name: Zip Wpf
      run: Compress-Archive -Path ./publish/wpf/* -DestinationPath TypeCode.Wpf_${{ steps.previoustag.outputs.tag }}.zip
    
    - name: Copy / Rename Wpf Setup
      run: Copy-Item ./publish/setup/wpf/TypeCode.Wpf.Setup.msi -Destination TypeCode.Wpf.Setup_${{ steps.previoustag.outputs.tag }}.msi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.previoustag.outputs.tag }}
        release_name: Release ${{ steps.previoustag.outputs.tag }}
        body: New Release
        draft: false
        prerelease: false
        
    - name: Upload Release Assets Wpf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Wpf_${{ steps.previoustag.outputs.tag }}.zip
        asset_name: TypeCode.Wpf.zip
        asset_content_type: application/zip
        
    - name: Upload Release Assets Wpf Setup
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Wpf.Setup_${{ steps.previoustag.outputs.tag }}.msi
        asset_name: TypeCode.Wpf.Setup.msi
        asset_content_type: application/octet-stream
        
    - name: Upload Release Assets Console
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Console_${{ steps.previoustag.outputs.tag }}.zip
        asset_name: TypeCode.Console.zip
        asset_content_type: application/zip
        
    - name: Upload Release Assets Console Interactive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Console.Interactive_${{ steps.previoustag.outputs.tag }}.zip
        asset_name: TypeCode.Console.Interactive.zip
        asset_content_type: application/zip