name: Release

on:
  push:
      tags:
        - 'v*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF//./_}
    - uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-text: ${{ steps.vars.outputs.tag }}
        refs/tags/: ""
    - run: echo ${{ steps.sub.outputs.result }}
    
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.sub.outputs.result }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
        echo ${{ steps.sub.outputs.result }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Build Wpf
      run: dotnet build --configuration Release -o publish/wpf ./src/TypeCode.Wpf

    - name: Build Console
      run: dotnet build --configuration Release -o publish/console ./src/TypeCode.Console
      
    - name: Test
      run: dotnet test --verbosity normal
      
    - name: Zip Wpf
      run: zip -r TypeCode.Wpf_${{ steps.sub.outputs.result }} ./publish/wpf

    - name: Zip Console
      run: zip -r TypeCode.Console_${{ steps.sub.outputs.result }} ./publish/console
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: New Release.
        draft: false
        prerelease: false
        
    - name: Upload Release Assets Wpf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Wpf_${{ steps.sub.outputs.result }}.zip
        asset_name: TypeCode.Wpf_${{ steps.sub.outputs.result }}.zip
        asset_content_type: application/zip
        
    - name: Upload Release Assets Console
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Console_$_${{ steps.sub.outputs.result }}.zip
        asset_name: TypeCode.Console_${{ steps.sub.outputs.result }}.zip
        asset_content_type: application/zip
