name: Release

on:
  push:
      tags:
        - 'v*'
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Latest Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Install NuGet Client
      uses: nuget/setup-nuget@v1
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Remove Github NuGet Source
      run: |
        dotnet nuget remove source localPackages

    - name: Add Github NuGet Source
      run: dotnet nuget add source --username byCrookie --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/byCrookie/index.json"

    - name: Use Github Build Props
      run: |
        Remove-Item Directory.Build.props
        Rename-Item -Path Github.Directory.Build.props -NewName Directory.Build.props
        
    - name: Use Github Packages Props
      run: |
        Remove-Item Directory.Packages.props
        Rename-Item -Path Github.Directory.Packages.props -NewName Directory.Packages.props

    - name: Build Wpf
      run: dotnet build --configuration Release -o publish/wpf ./src/TypeCode.Wpf
      
    - name: Build Wpf Setup
      run: |
        ./src/TypeCode.Wpf.Setup/DownloadAndExtractWix.ps1
        msbuild ./src/TypeCode.Wpf.Setup -p:SolutionDir=M:\Development\Home\TypeCode\,Configuration=Release
        Copy-Item ./src/TypeCode.Wpf.Setup/bin/Release/TypeCode.Wpf.Setup.msi -DestinationPath publish/setup/wpf/TypeCode.Wpf.Setup.msi

    - name: Build Console
      run: dotnet build --configuration Release -o publish/console ./src/TypeCode.Console

    - name: Build Console Interactive
      run: dotnet build --configuration Release -o publish/interactive ./src/TypeCode.Console.Interactive
      
    - name: Test
      run: dotnet test --verbosity normal
      
    - name: Zip Wpf
      run: Compress-Archive -Path ./publish/wpf/* -DestinationPath TypeCode.Wpf_${{ steps.previoustag.outputs.tag }}.zip
      
    - name: Copy / Rename Wpf Setup
      run: Copy-Item ./publish/wpf/TypeCode.Wpf.Setup.msi -DestinationPath TypeCode.Wpf.Setup_${{ steps.previoustag.outputs.tag }}.msi

    - name: Zip Console
      run: Compress-Archive -Path ./publish/console/* -DestinationPath TypeCode.Console_${{ steps.previoustag.outputs.tag }}.zip

    - name: Zip Console Interactive
      run: Compress-Archive -Path ./publish/interactive/* -DestinationPath TypeCode.Console.Interactive_${{ steps.previoustag.outputs.tag }}.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.previoustag.outputs.tag }}
        release_name: Release ${{ steps.previoustag.outputs.tag }}
        body: New Release
        draft: false
        prerelease: false
        
    - name: Upload Release Assets Wpf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Wpf_${{ steps.previoustag.outputs.tag }}.zip
        asset_name: TypeCode.Wpf_${{ steps.previoustag.outputs.tag }}.zip
        asset_content_type: application/zip
        
    - name: Upload Release Assets Wpf Setup
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Wpf.Setup_${{ steps.previoustag.outputs.tag }}.msi
        asset_name: TypeCode.Wpf.Setup_${{ steps.previoustag.outputs.tag }}.msi
        asset_content_type: application/octet-stream
        
    - name: Upload Release Assets Console
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Console_${{ steps.previoustag.outputs.tag }}.zip
        asset_name: TypeCode.Console_${{ steps.previoustag.outputs.tag }}.zip
        asset_content_type: application/zip
        
    - name: Upload Release Assets Console Interactive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TypeCode.Console.Interactive_${{ steps.previoustag.outputs.tag }}.zip
        asset_name: TypeCode.Console.Interactive_${{ steps.previoustag.outputs.tag }}.zip
        asset_content_type: application/zip
